### ISSUE TITLE
Question about datasets. 

### ISSUE THREAD

**Issue by YifaSuoha962** [dmis-lab/PerceiverCPI#1]
Awesome work!
But I didn't find the datasets in your paper (Davis, KIBA, etc)，can you share these datasets for reproduction?

**Comment by quangnguyenbn99** [comment]
You can find the dataset in the supplementary. Due to the dataset's size, we cannot upload it.

**Comment by JackFang0815** [comment]
> You can find the dataset in the supplementary. Due to the dataset's size, we cannot upload it.

Could you please upload the split datasets to Google Driver or other places? Using the same datasets allows fair comparisons to be made in later papers. Thank you.

**Comment by ilya-eder** [comment]
@NathanielNguyen11 thanks for the awesome work!

The supplementary Google Disk drive you link [in Readme](https://github.com/dmis-lab/PerceiverCPI/blob/main/README.md?plain=1#L50) appears to be inactive; I wonder if by any chance there is an error in the link?

**Comment by quangnguyenbn99** [comment]
I am terribly sorry for the late reply. Due to the size of the dataset, I could not able to upload. The DeepPurpose is uploaded to the repository.
Please consider the Deeppupose SW to get the dataset (DAVIS/KIBA) (run `python dataset.py` inside the deeppurpose folder)
Hope it helps.
