### ISSUE TITLE
How to modify Attention blocks

### ISSUE THREAD

**Issue by thaomaidang** [dmis-lab/PerceiverCPI#10]
Hi Nguyen,

First of all, thank you for sharing this wonderful model. I have a question: In your model, there are three attention blocks (two cross-attentions and one self-attention). I would like to modify something in these blocks. Could you tell me where in your code I can modify the attention components, particularly the Perceiver parts? For example, assume we already have embeddings from Mol Graph, ECFP, and Protein (i.e., I extracted all of them to save time, and now I just want to focus on modifying the attention-related steps).

Thank you so much.

**Comment by quangnguyenbn99** [comment]
Thank you for your attention to our work. 
1. You might find the attention at this source: [https://github.com/dmis-lab/PerceiverCPI/blob/main/chemprop/models/CAB.py](url)
2. Suppose you already have the embeddings. You need to use an additional neural network to reduce their dimensionality to 1. After that, simply apply the attention mechanism as described in the paper.

**Comment by thaomaidang** [comment]
Thank you for your response =))
