### ISSUE TITLE
Classification task

### ISSUE THREAD

**Issue by muammar** [dmis-lab/PerceiverCPI#3]
Does your implementation work for classification tasks?

**Comment by quangnguyenbn99** [comment]
Hello @muammar,
Yes, the source code also supports classification tasks. To do so, you might need to modify the two augments:
`--metric: mse -> classification metrics ['auc', 'prc-auc','accuracy', 'cross_entropy', 'binary_cross_entropy']`
`--dataset_type regression-> classification `
Hope it helps!

**Comment by muammar** [comment]
Thank you. I realized after reading the source code that your implementation accounts for classification tasks.
