### ISSUE TITLE
About the CAB annotation

### ISSUE THREAD

**Issue by DBpackage** [dmis-lab/PerceiverCPI#6]
Hi, good to see you again!

I'm making my model based on your fantastic model! 
Thanks for giving wonderful insight for CPI task :)

BTW, In the CAB.py file. I found this annotation about cross-att:
<img width="1116" alt="image" src="https://github.com/dmis-lab/PerceiverCPI/assets/68315582/1e249737-9195-497b-b841-bdf2c8abe26d">

I'm confused with this annotation since with regard to this figure I understand that Key, Value must be came from same source and Query from the other source.
<img width="1323" alt="image" src="https://github.com/dmis-lab/PerceiverCPI/assets/68315582/b75f03e2-c70a-40b2-bb23-f6d06999f3a8">

And generally speaking, usually K,V comes from same source and Q comes from the other source in the transformer attention methods.

Is that just an typo? or I'm misunderstanding your method?

Thanks in advance,
sincerely!

**Comment by quangnguyenbn99** [comment]
Hi, Thank you for the finding, Yes, It was a typo. I confirm "K,V comes from same source and Q comes from the other source." is right!
The necessary update was made. 
![image](https://github.com/dmis-lab/PerceiverCPI/assets/32150689/7db1e022-09a5-42bb-b4f2-4916da3fefd3)
