### ISSUE TITLE
Question about the CAB.

### ISSUE THREAD

**Issue by BioBabyCode** [dmis-lab/PerceiverCPI#7]
Given that conventional cross-attention techniques are accompanied by various metrics, could you kindly provide an explanation for the incorporation of 1D CAB in PerceiverCPI?
Very interesting!

**Comment by quangnguyenbn99** [comment]
Hello, Mr/Ms.
The reason we introduced 1D CAB is as follows:
**Parameter Efficiency:** Small datasets often mean limited amounts of training data, and complex models with many parameters can easily overfit in such scenarios. 1D cross-attention models can be designed to have fewer parameters compared to their conventional counterparts, making them more suitable for small datasets as they are less prone to overfitting.

Thank you for raising an interesting question.

**Comment by BioBabyCode** [comment]
Hi,
Thank you for the answer. It helps a lot. I will refer to the technique for my further work. Would it be possible to ask more questions if needed?

**Comment by quangnguyenbn99** [comment]
Hello,
Sure, be my guest!
