### ISSUE TITLE
代码

### ISSUE THREAD

**Issue by 11140321** [dmis-lab/PerceiverCPI#8]
我想请问一下我运行代码使用的都是chemprop里面的，是进行DTA预测吗，那么提供的deeppupose里面的代码是什么用处呢

**Comment by quangnguyenbn99** [comment]
您好，
谢谢您的提问，我无法完全理解您的问题，因此我使用谷歌翻译来解释您的意思。
在这里，我们仅使用 chemprop 作为化合物信息提取的主干（Chemprop 不需要来自蛋白质的信息）。
Deeppurpose用于下载处理后的（KIBA、DAVIS）（将主单元转换为Plog单元）。
希望它能回答您的问题。

**Comment by 11140321** [comment]
Sorry to bother you, I mean I run train.py according to README, when I understand the code debug found that it only uses the files in chemprop, processing the data did not notice the ECFP fingerprint. There is another question, the code inside the CHEMPROP and Deeppurpose contains many sub-files and code, I feel a lot of run-time did not use, I would like to ask is I handle the problem？

**Comment by quangnguyenbn99** [comment]
I am so sorry that I could not understand your question clearly.
we modified the chemprop dataloader to adapt it to our purpose, you can find it at [MoleculeDataset](https://github.com/dmis-lab/PerceiverCPI/blob/main/chemprop/data/data.py#L305)
```  
def add_features(self) -> List[np.ndarray]:
        """
        Returns the features associated with each molecule (if they exist).

        :return: A list of 1D numpy arrays containing the features for each molecule or None if there are no features.
        """
        list_fingvecs = []
        for d in self._data:
            from rdkit import Chem, DataStructs
            features_vec = AllChem.GetMorganFingerprintAsBitVect(d.mol[0], radius = 2, nBits=2048)
            features = np.zeros((1,))
            DataStructs.ConvertToNumpyArray(features_vec, features)
            list_fingvecs.append(features)

        return list_fingvecs
